DROP TABLE IF EXISTS user_actions;
DROP TABLE IF EXISTS event_similarity;

CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    action_type VARCHAR NOT NULL CHECK (action_type IN ('VIEW', 'REGISTER', 'LIKE')),
    timestamp TIMESTAMP NOT NULL,
    UNIQUE (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS event_similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a BIGINT NOT NULL,
    event_b BIGINT NOT NULL,
    score DOUBLE PRECISION,
    timestamp TIMESTAMP NOT NULL,
    UNIQUE (event_a, event_b)
);