server:
  port: 0
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
spring:
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/event
    username: event
    password: event
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always


